main:
  - name: A WORLD PIECE
    url: 'https://apx.wp.computer'
    weight: 2
  - name: THE UNIVERSAL PIECE
    url: 'https://apx.up.computer'
    weight: 1
  - name: A WORLD PIECE COMPUTER
    url: 'https://a.wp.computer'
    weight: 3
  - name: posts
    url: /posts/
    weight: 4
  - name: docs
    url: /docs/
    weight: 5
  - name: $
    url: 'https://time-machine-for-peace.myshopify.com'
    weight: 6
